apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server
  namespace: iperf
spec:
  selector:
    matchLabels:
      app: iperf-server
  replicas: 1
  template:
    metadata:
      labels:
        app: iperf-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - iperf-client
            topologyKey: kubernetes.io/hostname
      containers:
        - name: iperf-server
          image: quay.io/randomparity/iperf-server:latest
          env:
          - name: IPERF_PROTOCOL
            value: tcp
          - name: IPERF_PORT
            value: "5001"
          ports:
            - containerPort: 5001
